### ISSUE TITLE
> хуйня, скопировал - не работает

### ISSUE THREAD

**Issue by Rosto4eks** [EgrShishov/ModernApplicationDevelopmentPlatforms#2]
> хуйня, скопировал - не работает
А зачем копировал?
Проверить на плагиат

_Originally posted by @B0YnextDoor in https://github.com/EgrShishov/ModernApplicationDevelopmentPlatforms/issues/1#issuecomment-2326851029_

**Comment by EgrShishov** [comment]
Idi naxuy x3

**Comment by Rosto4eks** [comment]
разобрались, автор пидорас, все равно не работает
